common:
  # Splunk index to write to
  splunkIndex: "sbb_atlas_internal_prod_events"
  # spring profile for the environment
  springProfilesActive: "prod"
  # Pod Instances Count
  replicas: 2

frontend:
  routeHost: 'atlas.sbb-cloud.net'
  publicRoute: 'atlas.app.sbb.ch'
  atlasApiUrl: 'https://atlas.api.sbb.ch:443'
  apiClientId: 'ab56f386-eefb-4ea9-b3ad-6d8323ad4c1a'
  apiScope: 'openid profile email offline_access api://f3cdcb3e-1e95-4591-b664-4526d00f5d66/.default'
  clusterLoadBalancer: 'public-maggie.app.sbb.ch'
  replicas: 2
  instanaKey: 'KYVhA85uS6CiOtFVzmkGEw'
