common:
  # Maximal CPU ie 1 for 1 Core
  cpuMax: "1"
  # Minimal CPU ie. 1m for 1 Milicore
  cpuMin: "100m"
  # Image Pull Policy
  imagePullPolicy: "Always"
  # Maximal Memory ie 1G for 1 Gigabyte
  memoryMax: "1G"
  # Minimal Memory ie 1M for 1 Megabyte
  memoryMin: "256M"
  # Pod Instances Count
  replicas: 1

gateway:
  # Name of the Dockerimge in bin.sbb.ch/dockerrepo
  name: "gateway"
  # LIVENESS_PROBE
  livenessProbe: "actuator/health"
  # READYNESS_PROBE
  readynessProbe: "actuator/health"
  # Application Port
  port: 8888

lineDirectory:
  # Name of the Dockerimge in bin.sbb.ch/dockerrepo
  name: "line-directory"
  # LIVENESS_PROBE
  livenessProbe: "actuator/health"
  # READYNESS_PROBE
  readynessProbe: "actuator/health"
  # Application Port
  port: 8082

businessOrganisationDirectory:
  # Deploy BusinessOrganisations
  enabled: true
  # Name of the Dockerimge in bin.sbb.ch/dockerrepo
  name: "business-organisation-directory"
  # LIVENESS_PROBE
  livenessProbe: "actuator/health"
  # READYNESS_PROBE
  readynessProbe: "actuator/health"
  # Application Port
  port: 8083

mail:
  # Name of the Dockerimge in bin.sbb.ch/dockerrepo
  name: "mail"
  # LIVENESS_PROBE
  livenessProbe: "actuator/health"
  # READYNESS_PROBE
  readynessProbe: "actuator/health"
  # Application Port
  port: 8084

frontend:
  # Name of the Dockerimge in bin.sbb.ch/dockerrepoted"
  name: "atlas-frontend"
  # Pod Instances Count
  replicas: 1
  # Used to deploy the Angular with production flag
  production: true