spring:
  datasource:
    url: jdbc:postgresql://scheduling-prod.czdfgxj0x1zx.eu-central-1.rds.amazonaws.com
    username: ${DB_USER}
    password: ${DB_PWD}
auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
atlas:
  client:
    gateway:
      url: "http://gateway:8888"