spring:
  datasource:
    url: jdbc:postgresql://scheduling-int.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/scheduling
    username: ${DB_USER}
    password: ${DB_PWD}
auth:
  audience:
    service-name: 733b361e-a067-4882-bb00-6bbaf36a007f
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
atlas:
  client:
    gateway:
      url: "http://gateway:8888"