apiVersion: v2
appVersion: 0.15.0-SNAPSHOT
description: A Helm chart for the line-directory application
name: atlas
# The effective version will be computed during Helm generation
version: 0.15.0-SNAPSHOT
# This is only added to make `helm lint` happy - configure your own icon!
icon: http://acme.org/replaceme.jpg
