logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{X-B3-TraceId:-} spanid=%X{X-B3-SpanId:-} message="%m"%n
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: http://localhost:4200,https://dev.atlas.sbb-cloud.net,https://developer-int.sbb.ch
gateway:
  routes:
    timetable-field-number: http://timetable-field-number-backend:8080
    line-directory: http://line-directory-backend:8082