spring:
  datasource:
    url: jdbc:postgresql://business-organisation-directory-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/business_organisation_directory
    username: ${DB_USER}
    password: ${DB_PWD}
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n