kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
    clew.sbb.ch/cluster-independent-dns: 'true'
  name: {{ .Values.frontend.name }}
spec:
  host: '{{ .Values.frontend.routeHost }}'
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: '{{ .Values.frontend.name }}'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    router.clew.sbb.ch/type: sbb-aws-alb-public
  annotations:
    clew.sbb.ch/cluster-independent-dns: 'true'
    external-dns.alpha.kubernetes.io/alias: 'true'
    external-dns.alpha.kubernetes.io/target: '{{ .Values.common.clusterLoadBalancer }}'
  name: {{ .Values.frontend.name }}-public
spec:
  host: '{{ .Values.frontend.publicRoute }}'
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: '{{ .Values.frontend.name }}'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
