{{- if .Values.businessOrganisationDirectory.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.businessOrganisationDirectory.name }}'
spec:
  ports:
  - name: '{{ .Values.businessOrganisationDirectory.port }}-tcp'
    port: {{ .Values.businessOrganisationDirectory.port }}
    protocol: TCP
    targetPort: {{ .Values.businessOrganisationDirectory.port }}
  selector:
    app: '{{ .Values.businessOrganisationDirectory.name }}'
    deploymentconfig: '{{ .Values.businessOrganisationDirectory.name }}'
  sessionAffinity: None
  type: ClusterIP
{{- end }}