server:
  port: 6969
spring:
  application:
    name: api-auth-gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8888
          predicates:
            - Path=/**
      default-filters: AssureAuthorizationFilter
  # Client Credentials for Unauthenticated Requests
  security:
    oauth2:
      client:
        registration:
          sbb:
            client-id: 39ff0746-6345-4204-afd3-3e114e5ab715
            client-secret: super-secret
            authorization-grant-type: client_credentials
            scope: api://87e6e634-6ba1-4e7a-869d-3348b4c3eafc/.default
        provider:
          sbb:
            token-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/oauth2/v2.0/token

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
info:
  app:
    name: api-auth-gateway
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO